---
name: build-image-for-backend
run-name: Build and Push docker image for backend
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  linux_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: version-step
        uses: michmich112/extract-version@main
        with:
          version-file: ./version.txt
          schema: major.minor.build

      - name: Show Version of Backend
        run: |
          echo "version -> $BACKEND_VERSION"
        env:
          BACKEND_VERSION: ${{ steps.version-step.outputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          BACKEND_VERSION: ${{ steps.version-step.outputs.version }}
        with:
          platforms: linux/arm64, linux/amd64
          push: true
          tags: axelnemes/msc-onlab-backend:${{ env.BACKEND_VERSION }}
