---
name: coverage
run-name: Coverage Backend
on:
  workflow_call:
    secrets:
      COVERALLS_REPO_TOKEN:
        required: true
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make packages

      - name: Create coverage file
        run: |
          make coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
