---
name: test-and-coverage-backend
run-name: Testing and creating Coverage for Backend

on:
  push:   # set back to "pull_request" when finished work
    paths:
      - 'api/**'
      - 'Dockerfile'
      - 'version.txt'

  pull_request:
    types:
      - opened
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make packages

      - name: Test with pytest
        run: |
          make test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make packages

      - name: Create coverage file
        run: |
          make coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2

  # build-images-for-backend:
  #   needs: [test, coverage]
  #   uses: ./.github/workflows/build-image-for-backend.yml
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}