---
name: coverage
run-name: Test and Creating Coverage for Backend

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  test:
    uses: ./.github/workflows/test-backend.yml

  coverage:
    uses: ./.github/workflows/coverage-backend.yml
    secrets:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  # build-images-for-backend:
  #   needs: [test, coverage]
  #   uses: ./.github/workflows/build-image-for-backend.yml
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}